fs/nfs/nfs4proc: Fix Build Error
Fix Error For Commit 789e380

Log Error:

../fs/nfs/nfs4proc.c:5891:8: error: extraneous ')' before ';'
 5891 |                            0);
      |

Signed-off-by: Syahid <syahidselaluspd708@gmail.com>